title: Chanho Suh
email: csuh.web@gmail.com
description: Chanho Suh
url: "https://chanhosuh.com"
twitter: chanhosuh

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
